default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: <%= ENV['DB_DATABASE_DL'] %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE_TS'] %>

production:
  <<: *default
  database: <%= ENV['DB_DATABASE_PR'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

