default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']

development:
  <<: *default
  database: crowd_funding_development

test:
  <<: *default
  database: crowd_funding_test

production:
  <<: *default
  database: crowd_funding_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

